DEBUG 2021-04-23 17:19:50.859 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-23 17:19:50.860 UTC: 	 Running on: Linux cmslpc117.fnal.gov 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 08:00:44 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-04-23 17:19:50.860 UTC: 	 Executing command: 'status'
DEBUG 2021-04-23 17:19:50.863 UTC: 	 Found CRAB cache file /uscms/home/ballmond/.crab3
ERROR 2021-04-23 17:19:50.867 UTC: 	 Error: test/crab_VBFHToTauTau_MINIAODSIM is not a valid CRAB project directory.
ERROR 2021-04-23 17:19:50.868 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: test/crab_VBFHToTauTau_MINIAODSIM is not a valid CRAB project directory.
INFO 2021-04-23 17:19:50.870 UTC: 	 Log file is /uscms_data/d3/ballmond/test-dir/CMSSW_10_2_16_UL/src/VBFTau/NtupleMaker/python/test/crab.log
DEBUG 2021-04-23 17:20:10.092 UTC: 	 CRAB Client version: v3.210323
DEBUG 2021-04-23 17:20:10.092 UTC: 	 Running on: Linux cmslpc117.fnal.gov 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 08:00:44 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-04-23 17:20:10.092 UTC: 	 Executing command: 'status'
DEBUG 2021-04-23 17:20:10.092 UTC: 	 Found CRAB cache file /uscms/home/ballmond/.crab3
ERROR 2021-04-23 17:20:10.095 UTC: 	 Error: test/crab_VBFHToTauTau_GENSIMRAW_test is not a valid CRAB project directory.
ERROR 2021-04-23 17:20:10.095 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210323.00/lib/CRABClient/Commands/SubCommand.py", line 639, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: test/crab_VBFHToTauTau_GENSIMRAW_test is not a valid CRAB project directory.
INFO 2021-04-23 17:20:10.098 UTC: 	 Log file is /uscms_data/d3/ballmond/test-dir/CMSSW_10_2_16_UL/src/VBFTau/NtupleMaker/python/test/crab.log
